// Debe mantenerse en sincronía con la lista de íconos disponibles en
// frontend/src/lib/categoryIcons.tsx (los nombres corresponden a componentes de lucide-react).
export const CATEGORY_ICON_NAMES = [
  "Dumbbell",
  "Cpu",
  "Home",
  "Shirt",
  "Sparkles",
  "Baby",
  "PawPrint",
  "Gamepad2",
  "HeartPulse",
  "Briefcase",
  "Wrench",
  "Car",
  "BookOpen",
  "Music",
  "Camera",
  "Utensils",
  "Palette",
  "Gift",
  "Watch",
  "Glasses",
  "Bike",
  "Plane",
  "ShoppingBag",
  "Smartphone",
  "Tv",
  "Lamp",
  "Flower2",
  "Coffee",
  "Puzzle",
  "Tag",
] as const;
